set nocompatible            " Turn off vi compatibility mode
filetype off                " Interferes with Pathogen, so turn off
call pathogen#helptags()    " Generate help tags for plugins
call pathogen#infect()      " Load all the plugins
filetype on                 " Reenable filetype
filetype indent on
filetype plugin on

" Directories for swp files
set backupdir=~/.vim/backup
set directory=~/.vim/backup

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

"turn numbers on
set number

" Tab completion
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc,*.class,.svn,vendor/gems/*,node_modules/*

" Without setting this, ZoomWin restores windows in a way that causes
" equalalways behavior to be triggered the next time CommandT is used.
" This is likely a bludgeon to solve some other issue, but it works
set noequalalways

" ZoomWin configuration
map <Leader><Leader> :ZoomWin<CR>

" Remember last location in file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif
endif

" Inserts the path of the currently edited file into a command
" Command mode: Ctrl+P
cmap <C-P> <C-R>=expand("%:p:h") . "/" <CR>

" Fast editing of the .vimrc
map <leader>v :e! ~/.vimrc<cr>

" When vimrc is edited, reload it
autocmd! bufwritepost vimrc source ~/.vim/vimrc

"NERDTree configuration
let NERDTreeIgnore=['\.rbc$', '\~$']
map <Leader>n :NERDTreeToggle<CR>

"ctlp i.e. commandT replacement
map <Leader>t :CtrlP<Enter>

"set easy motion to single leader rather than double
let g:EasyMotion_leader_key = '<Leader>'

"for toggling tagbar
nmap <Leader>m :TagbarToggle<CR>

"resize windows
if bufwinnr(1)
  map + <C-W>+
  map - <C-W>-
  map < <C-W><
  map > <C-W>>
endif


"color
color Tomorrow-Night


"NERDcommenter configuration
"toggle = leader c space

"surround
"cs'<tag>  = 'this' -> <tag>this</tag>
"cst' = <tag>this</tag> -> 'this'
